import 'package:flutter/material.dart';


class Product {
  final String image, title, description, url;
  final int price, size, id, color1, color2, color3;
  final Color color;
  final bool favorite;
  Product({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.size,
    required this.color,
    required this.url,
    required this.favorite,
    required this.color1,
    required this.color2,
    required this.color3,
  });
}

List<Product> products = [
  Product(
    favorite: true,
    id: 0,
    title: "Arbys",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/rest0.png",
    color: Color(0xFF3D82AE),
    url:'https://www.arbys.com/deals/',
  color1: 0,
    color2: 0,
    color3: 250,



  ),
  Product(
    favorite: false,
    id: 1,
    title: "Red Lobster",
    price: 234,
    size: 8,
    description: dummyText,
    image: "assets/images/rest1.png",
    color: Color(0xFFD3A984),
    url: 'https://www.redlobster.com/rewards',
    color1: 0,
    color2: 0,
    color3: 250,),
  Product(
    favorite: false,
    id: 2,
    title: "Red Robin",
    price: 234,
    size: 10,
    description: dummyText,
    image: "assets/images/rest2.png",
    color: Color(0xFF989493),
    url: "https://www.redrobin.com/rewards",
    color1: 0,
    color2: 0,
    color3: 250,),
  Product(
      favorite: false,
      id: 3,
      title: "Applebee's",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/images/rest3.png",
      color: Color(0xFFE6B398),
      url: "https://www.applebees.com/en/sign-up",
    color1: 150,
    color2: 15,
    color3: 150,),
  Product(
      favorite: false,
      id: 4,
      title: "Au Bon Pain",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/rest4.png",
      color: Color(0xFFFB7883),
      url: "http://aubonpain.fbmta.com/members/UpdateProfile.aspx?Action=Subscribe&_Theme=21474836609&inputsource=w",
    color1: 0,
    color2: 250,
    color3: 0,),
  Product(
      favorite: false,
      id: 5,
      title: "Baja Fresh",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/rest5.png",
      color: Color(0xFFAEAEAE),
      url: "https://www.bajafresh.com/clubbaja/",
    color1: 0,
    color2: 250,
    color3: 0,
  ),
  Product(
      favorite: false,
      id: 6,
      title: "Johnny Rockets",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/rest6.png",
      color: Color(0xFFD3A984),
      url: "https://www.johnnyrockets.com/promotions/rocket-eclub",
    color1: 0,
    color2: 250,
    color3: 0,
  ),
  Product(
      favorite: false,
      id: 7,
      title: "The Noodle Company",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/rest7.png",
      color: Color(0xFFAEAEAE),
      url: "https://www.noodles.com/rewards/",
    color1: 250,
    color2: 0,
    color3: 0,
  ),
  Product(
      favorite: false,
      id: 8,
      title: "Au BOn Pain",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/rest8.png",
      color: Color(0xFF3D82AE),
      url: "http://aubonpain.fbmta.com/members/UpdateProfile.aspx?Action=Subscribe&_Theme=21474836609&inputsource=w",
    color1: 250,
    color2: 0,
    color3: 0,
  ),
  Product(
      favorite: false,
      id: 9,
      title: "Papa Gino's",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/rest9.png",
      color: Color(0xFFD3A984),
      url: "https://www.papaginos.com/rewards",
    color1: 250,
    color2: 0,
    color3: 0,
  ),

];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";